# Generated by Django 4.2.5 on 2023-09-29 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa_sali', models.CharField(max_length=255, unique=True)),
                ('pojemnosc_sali', models.IntegerField()),
                ('rzutnik_dostepny', models.BooleanField(default=False)),
            ],
        ),
    ]
